[base]
log_level = "DEBUG" # 日志等级
debug = false       # 是否开启调试模式，开启后会保存图片到本地文件夹
map_debug = false   # 是否开启地图选择调试模式，开启后运行脚本时会先进行飞图操作
kick_mode = 0       # 需要填写下方配置的索引值，第一套配置索引为0，第二套配置索引为1


[key]
"职业技能按键" = "v"
"未充能近战按键" = "c"
"跳隐身按键" = "x"
"终结技按键" = "g"
"埋头表情按键" = "down" # 引号里可以填写up/right/down/left


[image]
"x技能识别阈值" = 0.9 # 不建议改动这个值

"连续检测boss血条次数" = 2
"连续检测玩家血条次数" = 2

"玩家血条颜色范围" = [[200, 200, 200], [255, 255, 255]]
"玩家终结技血条颜色范围" = [[0, 190, 190], [0, 200, 200]]
"BOSS血条颜色范围" = [[150, 90, 10], [240, 180, 80]]


[image.1440p]
"X技能坐标边界" = [252, 1233, 334, 1318]
"玩家血条坐标边界" = [994, 134, 1094, 144]
"BOSS血条坐标边界" = [1250, 1295, 1350, 1305]


[image.1080p]
"X技能坐标边界" = [189, 924, 250, 987]
"玩家血条坐标边界" = [745, 100, 820, 107]
"BOSS血条坐标边界" = [937, 971, 1012, 978]


[map_select]
"鼠标移动和单击时间间隔" = 0.3
"打开地图后等待时间" = 1
"选择废墟等待时间" = 0.3
"选择难度时间间隔" = 1.5
"飞图点击开始按钮延迟" = 3


[map_select.1440p]
"鼠标x轴坐标" = 2360
"难度选项卡坐标" = [1960, 1110]
"大师难度选项坐标" = [455, 460]
"开始按钮坐标" = [2180, 1210]
"F进度坐标" = [1805, 1115]


[map_select.1080p]
"鼠标x轴坐标" = 1770
"难度选项卡坐标" = [1470, 832]
"大师难度选项坐标" = [341, 345]
"开始按钮坐标" = [1635, 907]
"F进度坐标" = [1353, 836]


# 这里准备了两套配置，在前面的"启用的配置"中选择要启用的配置
[kick]
"最大连续失败次数" = 20     # 眉笔机制，连续失败次数超过这个值时会重新进本
"闪身后破隐等待时间" = 1.5
"终结后最长等待结算时间" = 35
"未检测到护盾后的等待时间" = 10
"等待结算超时后的等待时间" = 10

# 第一套配置，索引为0
# https://www.bilibili.com/video/BV1cH4y1G7ZP
# https://space.bilibili.com/80661500
[[kick.commands]]
"开BOSS鼠标偏移" = [-42, -40]
"隐身后往左走时间" = 0.64
"隐身后往前走时间" = 1.91

"射击黄血鼠标偏移" = [260, 86]
"等待黄血刷新时间" = 5.605

"躲藏第一段位移镜头偏移" = [-905, 0]
"躲藏第一段位移时间" = 1.82

"躲藏第二段位移镜头偏移" = [130, 0]
"躲藏第二段位移时间" = 3


# 第二套配置，索引为1
[[kick.commands]]
"开BOSS鼠标偏移" = [-42, -40]
"隐身后往左走时间" = 0.5
"隐身后往前走时间" = 1.83

"射击黄血鼠标偏移" = [188, 72]
"等待黄血刷新时间" = 5.805

"躲藏第一段位移镜头偏移" = [-850, 0]
"躲藏第一段位移时间" = 1.8

"躲藏第二段位移镜头偏移" = [250, 0]
"躲藏第二段位移时间" = 3
